name: Reusable PR Validation

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '22'
      python-version:
        type: string
        required: false
        default: '3.13'
      pnpm-version:
        type: string
        required: false
        default: 'latest'

jobs:
  validate:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: juninmd/base-actions/validate-pr@main